import { BaseDTO } from './base.dto';

export class PostDTO extends BaseDTO {
  id?: number;
  userId: number;
  title: string;
  body: string;

  constructor(
    userId: number = 0,
    title: string = '',
    body: string = '',
    id?: number
  ) {
    super();
    this.userId = userId;
    this.title = title;
    this.body = body;
    this.id = id;
  }
}

/**
 * Make PostDTO - DTO for the creation a post (omit the ID that is generated by the server)
 */
export class CreatePostDTO extends BaseDTO {
  userId: number;
  title: string;
  body: string;

  constructor(userId: number = 0, title: string = '', body: string = '') {
    super();
    this.userId = userId;
    this.title = title;
    this.body = body;
  }
}

/**
 * UpdatePostDTO - DTO for update a POST (All of them are optionals)
 */
export class UpdatePostDTO extends BaseDTO {
  id?: number;
  userId?: number;
  title?: string;
  body?: string;

  constructor(
    data: { id?: number; userId?: number; title?: string; body?: string } = {}
  ) {
    super();
    this.id = data.id;
    this.userId = data.userId;
    this.title = data.title;
    this.body = data.body;
  }
}
